# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPNFHazhdM5T1zfrqo92GcKRXrEqlR-l
"""

# app.py
import io
import torch
import numpy as np
from PIL import Image
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import JSONResponse
from torchvision import transforms
from fastapi.middleware.cors import CORSMiddleware
app = FastAPI(title="MNIST CNN API")

#Allow frontend access
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

from model import MNISTModel

# Initialize FastAPI app
app = FastAPI(
    title="MNIST Digit Classifier API",
    description="Predict handwritten digits using a trained PyTorch model.",
    version="1.0"
)

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load the trained model
model = MNISTModel().to(device)
model.load_state_dict(
    torch.load("mnist_model_weights.pth", map_location=device)
)
model.eval()

# Image preprocessing pipeline
transform = transforms.Compose([
    transforms.Grayscale(num_output_channels=1),
    transforms.Resize((28, 28)),
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

# Class labels
classes = list(range(10))


@app.get("/")
def home():
    return {
        "message": "MNIST FastAPI is running!",
        "usage": "Send a POST request to /predict with a digit image."
    }


@app.get("/health")
def health_check():
    return {"status": "healthy"}


@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    """
    Predict the digit from an uploaded image.
    """
    try:
        # Validate file type
        if not file.content_type.startswith("image/"):
            raise HTTPException(
                status_code=400,
                detail="File must be an image."
            )

        # Read and preprocess the image
        contents = await file.read()
        image = Image.open(io.BytesIO(contents)).convert("L")

        image = transform(image).unsqueeze(0).to(device)

        # Perform inference
        with torch.no_grad():
            outputs = model(image)
            probabilities = torch.softmax(outputs, dim=1)
            confidence, predicted = torch.max(probabilities, 1)

        return JSONResponse({
            "predicted_digit": int(predicted.item()),
            "confidence": float(confidence.item())
        })

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))